### ISSUE TITLE
Update Sidekiq 6

### ISSUE THREAD

**Issue by CR4567** [iMacTia/sidekiq-logstash#16]
Hi,
is there a chance that you would update your gem dependencies for sidekiq > 6?
I like the way your gem is working and don't want to miss it.

**Comment by iMacTia** [comment]
Hi @CR4567, yes of course, I wasn’t aware a new major release of Sidekiq was out. I’ll have a look today and hopefully it will be a smooth update

**Comment by CR4567** [comment]
Hi @iMacTia, did you find our anything about the necessary updates? 
Do you need any support?

**Comment by iMacTia** [comment]
Hi @CR4567, I've created #17 and Travis is happy, however I was hoping to get some real-world feedback before pushing the update.
Do you think you can test the branch in your project and tell us if there are any obvious issues?

**Comment by CR4567** [comment]
Hey, sure I will setup my test environment with the new version.
I can give you some feedback how it works by tomorrow.

**Comment by iMacTia** [comment]
That would be awesome!
Thanks 😄

**Comment by CR4567** [comment]
hm... I did some tests with the updated versions. Unfortunately when I update to sidekiq 6 in combination with sidekiq-logstash, my Jobs aren't handled anymore. I don't get any error, it's just not doing anything after starting the service...
I will try to go into more detail when I have some more time.

**Comment by iMacTia** [comment]
That doesn't sound good, I hope it's just something with settings!
Thanks for giving it a go, looking forward to hearing more feedback

**Comment by silviusimeria** [comment]
Sidekiq `6.0` introduced, yet again, braking changes regarding logging.
 
More information can be found here: https://github.com/mperham/sidekiq/blob/master/6.0-Upgrade.md
and here: https://github.com/mperham/sidekiq/wiki/Logging

They have created a new logger(looks like a proper implementation this time) and introduced the ability to pass a formatter, also they provide some basic Formatters. (`Pretty WithoutTimestamp JSON`)

Using the `LogstashFormatter` (JSON) formatter we provided with this gem with their logger, works, but obviously we are losing all the functionality of our logger (filtering, additional parameters logged etc.) so that does not do much at all.

Unfortunately, we cannot simply pass our `Sidekiq::LogstashJobLogger` as the logger for Sidekiq because they have implemented a propper logger and ours is not compatible anymore.

So in order to keep the only additional features this gem provides now to Sidekiq 6 (filtering and custom parameters configuration), I think we need to create a new logger that inherits from the new `Sidekiq::Logger` and add these features. 

I can find the time to do that when and if we upgrade to Sidekiq 6 here if nobody does that before :)

**Comment by iMacTia** [comment]
Thanks for the extensive research @silviusimeria, sorry to hear this means it's not as easy as initially thought.

Another thing to keep in mind is that tests were all green, which means we might not be testing our logger functionalities (filtering, additional parameters logged etc.) the right way.

This should also be fixed in scope of this work

**Comment by iMacTia** [comment]
@silviusimeria @CR4567 I finally got to work to a new project and wanted to use Sidekiq 6, so I've spent some time fixing this myself 😄 

Indeed, the old tests were not testing the actual integration between Sidekiq and this gem, we were mocking too much.
PR #19 fixes that, by using the Sidekiq internal processor.
I've also upgraded the `LogstashJobLogger` as suggested above to be compatible with Sidekiq 6 new logging system.
Finally, I took the opportunity to upgrade the gem a bit across the line 👍 

Unfortunately, all these changes were quite complex and it was not possible for me to keep supporting Sidekiq 3, 4 and 5.
I've thus decided to drop support for all those in the new branch and if we're happy with the changes that could be released as a v2.0 of the gem.
