### ISSUE TITLE
Add logging when job starts

### ISSUE THREAD

**Issue by stanhu** [iMacTia/sidekiq-logstash#4]
I noticed sidekiq-logstash doesn't log an event when a job starts: https://github.com/iMacTia/sidekiq-logstash/blob/e3a5c706a77ea1559f5379e14b5b34f3bea2d552/lib/sidekiq/middleware/server/logstah_logging.rb#L12

That seems like valuable information. Is there any reason this isn't being done?

**Comment by iMacTia** [comment]
Hi @stanhu,
that's a good question. Main reason is that I wanted to achieve a 1-line-per-job log, similarly to what `lograge` does for rails logs. This makes the integration and organisation in Logstash/Kibana (ELK stack) easier, which is the one I was using.
I'd like to keep this as the default behaviour, however if you still think it would be better to have an "event started" log entry as well I can review a PR.
The only requirements for that would be:

1. Compatibility with Logstash (JSON format + `@timestamp` and `@version` fields)
2. To be enabled through configuration (and turned off by default).

**Comment by stanhu** [comment]
@iMacTia Thanks, makes sense. For your reference, I evaluated this gem and another one to determine what we wanted for GitLab: https://gitlab.com/gitlab-org/gitlab-ce/issues/20060#note_66026811

I used your code as a basis for https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/18121/diffs, so thanks for starting this project.

**Comment by stanhu** [comment]
We've seen issues where Sidekiq jobs get stalled, and having the "start" message is incredibly helpful to know what was running before things got clogged.

**Comment by iMacTia** [comment]
@stanhu I'm honoured you're considering one of my gems to be used in GitLab.

This gem was born as a small helper to be used in some of my production systems by me and my team.
We didn't have any fancy requirements so we ended up with a very simple gem and I never expected someone to use it. It was very useful for us in production though, especially combined with Kibana's powerful tools.

I'm happy for you to use the code as you wish, but please consider to publish your improvements back into the gem so that everyone will benefit, if that's possible of course.

I can also consider a merging/rebase of the gem into your organisation if that works better for you.

**Comment by mdibaiee** [comment]
Hi @iMacTia !

Thank you for this gem, we also are looking for this feature as well since we have started using this gem. I'm happy to send a pull-request to support this (maybe through a configuration flag). I would like to confirm that you are eager to have this in the repository, and if you are, I will send the pull-request.

**Comment by iMacTia** [comment]
Hi @mdibaiee, of course!

Improvements and contributions are always welcome! As far as you follow the guidelines I set out in my comment above I’d be more than happy to review and merge a PR 👍

Thanks for considering to contribute
